export const environment = {
  production: false,
  baseUrl: 'https://api.shortlyst.com/v1',
  apiKey: 'e3ebd9fdf9704775c7fd6bb4f20e1798',
  merchant: 'flipkart',
  mode: 'full',
  limit: 20,
  sortField: [{
    key: 'default'​,
    value: 'Default​'
  }, {
    key: 'price​',
    value: 'Price',
  }, {
    key: 'discounts',
    value: 'discountFilter'​,
  }, {
    key: 'newArrivalsRank​',
    value: 'New Arrivals'
  }, {
    key: 'trendingRank​',
    value: 'Trending'
  }, {
    key: 'categoryRank',
    value: 'By Category Rank'
  }, {
    key: 'bestsellersRank​',
    value: 'By Sellers Rank'
  }],
  sortOrder: [{
    key: 'asc',
    value: 'Low to High'
  }, {
    key: 'desc',
    value: 'High to Low'
  }],
  genderFilter: [
    "women",
    "men",
    "girls",
    "boys"
  ],
  silhouetteFilter: [
    "western wear",
    "ethnic wear",
    "shoes",
    "handbags & clutches",
    "rings",
    "earrings",
    "t-shirts & polos",
    "lingerie & nightwear",
    "jewellery sets",
    "accessories",
    "bangles & bracelets",
    "pendants",
    "shirts",
    "tools & accessories",
    "make-up & nails",
    "necklaces",
    "sportswear",
    "skin care",
    "baby",
    "smart watches",
    "mobile accessories",
    "tops & tees",
    "bath & body",
    "health care",
    "trousers",
    "jeans",
    "innerwear",
    "fragrance",
    "hair care & styling",
    "shorts",
    "sweatshirts & hoodies",
    "socks",
    "dresses",
    "hair jewellery",
    "jackets & gilets",
    "computer components",
    "bedding, furniture & room decor",
    "wallets",
    "unstitched fabric",
    "storage",
    "jackets",
    "personal care",
    "socks, tights & leggings",
    "body jewellery",
    "mangalsutras & tanmaniyas",
    "cufflinks & shirt accessories",
    "bracelets",
    "suits & blazers",
    "bags & backpacks",
    "anklets"
  ],
  patternFilter: [
    "geometric print",
    "solid",
    "self design",
    "striped",
    "printed",
    "embellished",
    "floral print",
    "embroidered",
    "plain",
    "graphic print",
    "checkered",
    "polka print",
    "animal print",
    "textured"
  ],
  primaryColorFilter: [
    "multi color",
    "black",
    "blue",
    "grey",
    "brown",
    "white",
    "red",
    "pink",
    "yellow",
    "green",
    "violet",
    "orange",
    "skin",
    "turquoise",
    "purple",
    "indigo"
  ],
  fabricFilter: [
    "cotton",
    "polyester",
    "lycra",
    "nylon",
    "satin",
    "linen",
    "viscose",
    "spandex",
    "silk",
    "net",
    "wool",
    "polyamide",
    "blended",
    "elastane",
    "stretch",
    "rayon",
    "denim",
    "leather",
    "jersey",
    "crepe",
    "georgette",
    "chiffon",
    "acrylic",
    "jacquard",
    "synthetic",
    "fleece",
    "velvet",
    "mesh",
    "terylene",
    "canvas",
    "brasso",
    "cashmere",
    "suede"
  ],
  lowPriceFilter: [
    
  ],
  highPriceFilter:[

  ],
  discountFilter: [
    "10",
    "20",
    "30",
    "40",
    "50",
    "60",
    "70",
    "80",
    "90"
  ],
  size: [
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "28",
    "30",
    "32",
    "34",
    "36",
    "38",
    "40",
    "42",
    "L",
    "M",
    "XL",
    "S",
    "XXL",
    "Free",
    "XS",
    "5 - 6 Years",
    "6 - 7 Years",
    "7 - 8 Years",
    "4 - 5 Years",
    "36 Inches",
    "34 Inches",
    "3 - 4 Years",
    "3XL",
    "32 Inches",
    "2 - 3 Years",
    "38 Inches",
    "8 - 9 Years",
    "9 - 10 Years",
    "40 Inches"
  ],
  subSilhouetteFilter: [
    "rings",
    "earrings",
    "men's shoes",
    "t-shirts",
    "sarees",
    "lingerie & underwear",
    "shirts, tops & tees",
    "kurtas",
    "jewellery sets",
    "sling & cross-body bags",
    "leggings",
    "women's shoes",
    "bangles & bracelets",
    "dress material",
    "pendants",
    "clutches",
    "dresses",
    "handbags",
    "necklaces",
    "accessories",
    "casual shirts",
    "pants & capris",
    "nightwear",
    "jeans",
    "smart watches",
    "shorts",
    "bottoms",
    "belts & suspenders",
    "face",
    "backpack handbags",
    "screen guards",
    "lips",
    "ties",
    "sweatshirts & hoodies",
    "polos",
    "eye care",
    "baby boys 0-24m",
    "hair combs, wigs & accessories",
    "trousers",
    "tops & tees",
    "baby girls 0-24m",
    "sweaters",
    "tops, tees & shirts",
    "body",
    "track pants & trousers",
    "hair care",
    "formal shirts",
    "coats & jackets",
    "casuals",
    "make-up brushes & tools"
  ]
};
